import express from "express";

import superAdminRoute from "./superadmin/routes";
// import signinRoute from "./signin/signinRoute";
import forgotRoute from "./forgot-password/forgotRoute";
import teacherRoutes from "./admin/schoolauthroutes/teacherRoutes";
import studentRoutes from "./admin/schoolauthroutes/studentRoutes";
import accountRoutes from "./admin/schoolauthroutes/accountRoutes";
import transportRoutes from "./admin/schoolauthroutes/transportRoutes";
import hostelRoutes from "./admin/schoolauthroutes/hostelRoutes";
import assignmentRoute from "./dashboard/teacher/assignmentRoute";
import attendenceRoute from "./dashboard/teacher/attendenceRoute";
import classRoute from "./dashboard/teacher/classRoute";
import examRoute from "./dashboard/teacher/examRoute";
import gradeRoute from "./dashboard/teacher/gradeRoute";
import lessonRoute from "./dashboard/teacher/lessonRoute";
import subjectRoute from "./dashboard/teacher/subjectRoute";
import resultRoute from "./dashboard/teacher/resultRoute";
import eventRoutes from "./dashboard/admin/eventRoutes";
import annoumcmentRoutes from "./dashboard/admin/annoumcmentRoutes";
import paymentSecreateRoute from "./dashboard/admin/paymentSecreateRoute";
import getProfileRoute from "./signin/getProfileRoute";
import ticketRoutes from "./dashboard/superadmin/ticketRoutes";
import feebackRoutes from "./dashboard/superadmin/feebackRoutes";
import todoRoutes from "./dashboard/superadmin/todoRoutes";
import answerRoutes from "./dashboard/admin/answerRoutes";
import competitionRoutes from "./dashboard/admin/competitionRoutes";
import leaderboardRoutes from "./dashboard/admin/leaderboardRoutes";
import pyqRoutes from "./dashboard/admin/pyqRoutes";
import transactionRoutes from "./dashboard/admin/transactionRoutes";
import featuresRoutes from "./dashboard/admin/featuresRoutes";
import roadmapRoutes from "./dashboard/student/roadmapRoutes";
import topicRoutes from "./dashboard/student/topicRoutes";
import newspaperRoutes from "./dashboard/teacher/newspaperRoutes";
import quizresultRoutes from "./dashboard/teacher/quizresultRoutes";
import quizRoutes from "./dashboard/teacher/quizRoutes";
import doubtRoutes from "./dashboard/admin/doubtRoutes";
import libraryRoutes from "./admin/schoolauthroutes/libraryRoutes";
import bookcopyRoutes from "./dashboard/library/bookcopyRoutes";
import bookIssueRoutes from "./dashboard/library/bookIssueRoutes";
import bookRoutes from "./dashboard/library/bookRoutes";
import createAuthorRoutes from "./dashboard/library/createAuthorRoutes";
import disputeRoutes from "./dashboard/library/disputeRoutes";
import fineManagmentRoutes from "./dashboard/library/fineManagmentRoutes";
import assignTransportRoutes from "./dashboard/transport/assignTransportRoutes";
import busAttendenceRoutes from "./dashboard/transport/busAttendenceRoutes";
import busrouteRoutes from "./dashboard/transport/busrouteRoutes";
import busRoutes from "./dashboard/transport/busRoutes";
import busStopRoutes from "./dashboard/transport/busStopRoutes";
import conductorRoutes from "./dashboard/transport/conductorRoutes";
import driverRoutes from "./dashboard/transport/driverRoutes";
import inchargeRoutes from "./dashboard/transport/inchargeRoutes";
import accommodationRequestRoutes from "./dashboard/hostel/accommodationRequestRoutes";
import complaintController from "./dashboard/hostel/complaintController";
import hostelExpenseRoutes from "./dashboard/hostel/hostelExpenseRoutes";
import hostelFeesRoutes from "./dashboard/hostel/hostelFeesRoutes";
import hostelInventoryRoutes from "./dashboard/hostel/hostelInventoryRoutes";
import medicalEmergencyRoutes from "./dashboard/hostel/medicalEmergencyRoutes";
import outpassRequestRoutes from "./dashboard/hostel/outpassRequestRoutes";
import roomRoutes from "./dashboard/hostel/roomRoutes";
import visitorRoutes from "./dashboard/admin/visitor/visitorRoutes";
import departmentRoutes from "./dashboard/admin/hrm/departmentRoutes";
import designationsRoutes from "./dashboard/admin/hrm/designationsRoutes";
import dutiesRoutes from "./dashboard/admin/hrm/dutiesRoutes";
import payrollRoutes from "./dashboard/admin/hrm/payrollRoutes";
import { permit } from "../utils/jwt_utils";
import { Role } from "@prisma/client";
// import { injectUserByToken } from "../utils/jwt_utils";

// Create a main API router
const apiRouter = express.Router();

// apiRouter.use(injectUserByToken);

apiRouter.use("/administrator", permit(Role.superadmin), superAdminRoute);
// apiRouter.use(signinRoute);
apiRouter.use(forgotRoute);
apiRouter.use(teacherRoutes);
apiRouter.use(studentRoutes);
apiRouter.use(accountRoutes);
apiRouter.use(transportRoutes);
apiRouter.use(hostelRoutes);
apiRouter.use(assignmentRoute);
apiRouter.use(attendenceRoute);
apiRouter.use(classRoute);
apiRouter.use(examRoute);
apiRouter.use(gradeRoute);
apiRouter.use(lessonRoute);
apiRouter.use(subjectRoute);
apiRouter.use(resultRoute);
apiRouter.use(eventRoutes);
apiRouter.use(annoumcmentRoutes);
apiRouter.use(paymentSecreateRoute);
apiRouter.use(getProfileRoute);
// apiRouter.use(userRoutes);
apiRouter.use(ticketRoutes);
apiRouter.use(feebackRoutes);
apiRouter.use(todoRoutes);
apiRouter.use(answerRoutes);
apiRouter.use(competitionRoutes);
apiRouter.use(leaderboardRoutes);
apiRouter.use(pyqRoutes);
apiRouter.use(transactionRoutes);
apiRouter.use("/admin", featuresRoutes);
apiRouter.use(roadmapRoutes);
apiRouter.use(topicRoutes);
apiRouter.use(newspaperRoutes);
apiRouter.use(quizresultRoutes);
apiRouter.use(quizRoutes);
apiRouter.use(doubtRoutes);
apiRouter.use(libraryRoutes);
apiRouter.use(bookcopyRoutes);
apiRouter.use(bookIssueRoutes);
apiRouter.use(bookRoutes);
apiRouter.use(createAuthorRoutes);
apiRouter.use(disputeRoutes);
apiRouter.use(fineManagmentRoutes);
apiRouter.use(assignTransportRoutes);
apiRouter.use(busAttendenceRoutes);
apiRouter.use(busrouteRoutes);
apiRouter.use(busRoutes);
apiRouter.use(busStopRoutes);
apiRouter.use(conductorRoutes);
apiRouter.use(driverRoutes);
apiRouter.use(inchargeRoutes);
apiRouter.use(accommodationRequestRoutes);
apiRouter.use(complaintController);
apiRouter.use(hostelExpenseRoutes);
apiRouter.use(hostelFeesRoutes);
apiRouter.use(hostelInventoryRoutes);
apiRouter.use(medicalEmergencyRoutes);
apiRouter.use(outpassRequestRoutes);
apiRouter.use(roomRoutes);
apiRouter.use(visitorRoutes);
apiRouter.use(departmentRoutes);
apiRouter.use(designationsRoutes);
apiRouter.use(dutiesRoutes);
apiRouter.use(payrollRoutes);

export default apiRouter;
